version: '3'

services:

    #MySQL Service
    esculappio_db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        container_name: esculappio_db
        restart: always
        tty: true
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'esculappio'
            MYSQL_USER: 'admindb'
            MYSQL_PASSWORD: 'esculappio_db'
            MYSQL_ROOT_PASSWORD: 'esculappio_db'
        volumes:
            - ./docker/mysql/dbdata:/var/lib/mysql
            - ./docker/mysql/dumps:/docker-entrypoint-initdb.d
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    #Node Services
    main:
        container_name: main
        build:
            context: ./main
            dockerfile: Dockerfile
        restart: always
        tty: true
        environment:
            SERVICE_NAME: main
            SERVICE_TAGS: dev
        working_dir: /app
        ports:
            - '3000:3000'
        volumes:
            - ./main:/app
            - node_modules:/app/node_modules
        networks:
            - app-network

    #Nginx Service
    nginx:
        image: nginx:perl
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - main
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    node_modules:

